version: "3.7"

services:
  db:
    restart: always
    image: mysql:8.0
    container_name: alcatraz_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 4306:3306
  api:
    build: .
    container_name: alcatraz_api
    command: /bin/sh -c "rm -f /api/tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
    ports:
      - 8000:8000
    volumes:
      - .:/api
    depends_on:
      - db
